### ISSUE TITLE
Unable to import the extension to Qliksense server

### ISSUE THREAD

**Issue by ziadmohd** [johsund/CircularKPI#2]
I have tried to import the extension zip file to Qliksense server and I am getting an error I have checkd the log file and this is what i found

295 2.1.1.0 20160405T114153.600-0400    CAYRDCAPPSWV022 9f01b6d0-cf51-4013-bfae-81d61076d7f0    Command=Add extension;Result=500;ResultText=Error: StaticContentWeb 10a9fde0-0190-4268-98db-58c4421d99d3    0c7b6692-9e31-4cb2-9bb4-5ae313108e9b    0   NAMCAADM    zmohammad005    0   Not available   Repository  ManagementAccess    /qrs/extension/upload   Add extension   500  Exception of type # 
*_'Repository.Communication.StaticContent.StaticContentWebException' was thrown. (HTTP code: 500)   9f01b6d0-cf51-4013-bfae-81d61076d7f0
*_

**Comment by johsund** [comment]
Hi ziadmohd,

It looks like you're using version 2.1.1 of Qlik Sense. There was an issue with bringing in extensions including static filetypes that were not approved. In this case I think it's the readme file (md), sample app (qvf) or a few of the screenshots that I've included. If you delete those from your zip it should load fine. I'd recommend upgrading to Qlik Sense 2.2.3 though which has a number of improvements and fixes this issue. The extension loads in fine on my end.

Further description of the bug/feature in 2.1.1:
https://community.qlik.com/docs/DOC-12920
