### ISSUE TITLE
CircularKPI Ext

### ISSUE THREAD

**Issue by WalterColeman** [johsund/CircularKPI#3]
Question on the rings, 

1. Can I force into a single row for display purposes?

2. What do the various rings represent?

Thanks in advance

**Comment by johsund** [comment]
Hi Walter,

1. Not sure how you mean exactly. The structure of the text is not customizable without changing the code. 
2. Each ring represents 100%.. so if a KPI object has a ring and a half, it means 150%.

**Comment by WalterColeman** [comment]
Thanks you're #2 answered my question

**Comment by johsund** [comment]
Thanks Walter. Will close this issue down for now.
